/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.LocalTime;
import java.time.Period;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hammad
 */
public class SelectTimeslots extends javax.swing.JFrame {

    /**
     * Creates new form SelectTimeslots
     */
    Instructor T;
    ArrayList<Section> secList = new ArrayList<Section>();
    ArrayList<Course> courseList = new ArrayList<Course>();
    String day_ = "";
    String time_ = "";
    String venue_ = "";
    LocalTime TIME_;
    Course C_;
    int roomlmt_ = 0;

    public final void fillCList() {
        for (int i = 0; i < secList.size(); i++) {

            boolean flag = true;

            for (int j = 0; j < courseList.size(); j++) {
                if (courseList.get(j).getCode().equals(secList.get(i).getCourse().getCode())) {
                    flag = false;
                    break;
                }
            }

            if (flag) {
                courseList.add(secList.get(i).getCourse());
            }
        }
    }

    public SelectTimeslots(Instructor t, ArrayList<Section> sl) {
        initComponents();
        T = t;
        secList = sl;
        fillCList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        timing = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        venue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        sList = new javax.swing.JComboBox<>();
        cCode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instructor Home -> Select Timeslots");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("Select Timeslots");

        cList.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        cList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cListMouseReleased(evt);
            }
        });
        cList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cListActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Timing:");

        timing.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        timing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        day.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        day.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Day:");

        venue.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        venue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Venue:");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        sList.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Section" }));
        sList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sListMouseReleased(evt);
            }
        });
        sList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sListActionPerformed(evt);
            }
        });

        cCode.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Course code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(172, 172, 172)
                                            .addComponent(jLabel5)
                                            .addGap(32, 32, 32))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(sList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(venue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(day, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(cList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cCode, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timing, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(venue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cListActionPerformed
        // TODO add your handling code here:
        sList.removeAllItems();
        sList.addItem("Select Section");
        cCode.setText(" ");

        if (!cList.getSelectedItem().toString().equals("Select Course")) {

            cCode.setText(courseList.get(cList.getSelectedIndex() - 1).getCode());

            for (int i = 0; i < secList.size(); i++) {
                if (secList.get(i).getCourse().getName().equals(cList.getSelectedItem().toString())) {
                    sList.addItem(secList.get(i).getName());
                }
            }
        }

    }//GEN-LAST:event_cListActionPerformed

    private void cListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cListMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cListMouseReleased

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if (cList.getItemCount() == 1) {
            for (int i = 0; i < courseList.size(); i++) {
                cList.addItem(courseList.get(i).getName());
            }
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (cList.getSelectedItem().toString().equals("Select Course") || sList.getSelectedItem().toString().equals("Select Section")) {
            JOptionPane.showMessageDialog(null, "Please enter all fields");
        } else {
            Connection dbconn = Database.con();
            int userId = 0;
            int tId = 0;

            if (dbconn != null) {
                try {

                    PreparedStatement st;

                    st = dbconn.prepareStatement("UPDATE section SET instructorId = ? WHERE time = ? and day = ? and room = ?");

                    st.setInt(1, T.getId());
                    time_ += ":00";
                    st.setString(2, time_);
                    st.setString(3, day_);
                    st.setString(4, venue_);
                    st.executeUpdate();
                   
                    Section s = new Section(sList.getSelectedItem().toString(), day_, TIME_, venue_, roomlmt_, C_, T);
                    T.getSectionList().add(s);

                    JOptionPane.showMessageDialog(null, "Timeslot added successfully");

                    this.dispose();
                    new SelectTimeslots(T, secList).setVisible(true);

                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            } else {
                System.out.println("Connection not availabale");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sListMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sListMouseReleased

    private void sListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sListActionPerformed
        // TODO add your handling code here:
        timing.setText(" ");
        day.setText(" ");
        venue.setText(" ");

        if (sList.getSelectedItem() != null) {
            if (!sList.getSelectedItem().toString().equals("Select Section")) {

                for (int i = 0; i < secList.size(); i++) {
                    if (secList.get(i).getName().equals(sList.getSelectedItem().toString())) {

                        LocalTime lt = secList.get(i).getTime();
                        TIME_ = lt;
                        String secDay = "";

                        if (!cList.getSelectedItem().toString().contains(" Lab")) {
                            lt = lt.plusHours(1);
                            lt = lt.plusMinutes(30);

                            if (secList.get(i).getDay().equals("Monday")) {
                                secDay = ", Wednesday";
                            } else if (secList.get(i).getDay().equals("Tuesday")) {
                                secDay = ", Thursday";
                            } else if (secList.get(i).getDay().equals("Wednesday")) {
                                secDay = ", Friday";
                            }

                        } else {
                            lt = lt.plusHours(3);
                        }

                        timing.setText(secList.get(i).getTime().toString() + " - " + lt.toString());
                        time_ = secList.get(i).getTime().toString();
                        day.setText(secList.get(i).getDay() + secDay);
                        day_ = secList.get(i).getDay();
                        venue.setText(secList.get(i).getRoom());
                        venue_ = secList.get(i).getRoom();
                        C_ = secList.get(i).getCourse();
                        roomlmt_ = secList.get(i).getRoomLimit();
                        break;
                    }
                }
            }
        }

        //

    }//GEN-LAST:event_sListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], Instructor t, ArrayList<Section> sl) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTimeslots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTimeslots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTimeslots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTimeslots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTimeslots(t, sl).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cCode;
    private javax.swing.JComboBox<String> cList;
    private javax.swing.JLabel day;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> sList;
    private javax.swing.JLabel timing;
    private javax.swing.JLabel venue;
    // End of variables declaration//GEN-END:variables
}
