/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.time.LocalTime;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hammad
 */
public class ViewSectionsOfSelCourse extends javax.swing.JFrame {

    /**
     * Creates new form ViewSectionsOfSelCourse
     */
    Admin AD;
    String course;

    public final void fillTable() {
        DefaultTableModel tbModel = (DefaultTableModel) table.getModel();
        for (int i = 0; i < AD.getDept().getCourseList().size(); i++) {
            if (AD.getDept().getCourseList().get(i).getName().equals(course)) {
                for (int j = 0; j < AD.getDept().getCourseList().get(i).getSectionList().size(); j++) {
                    String instrName = " ";
                    if (AD.getDept().getCourseList().get(i).getSectionList().get(j).getInstructor() != null) {
                        instrName = AD.getDept().getCourseList().get(i).getSectionList().get(j).getInstructor().getName();
                    }

                    LocalTime lt = AD.getDept().getCourseList().get(i).getSectionList().get(j).getTime();
                    String secDay = "";

                    if (!AD.getDept().getCourseList().get(i).getSectionList().get(j).getCourse().getName().contains(" Lab")) {
                        lt = lt.plusHours(1);
                        lt = lt.plusMinutes(30);

                        if (AD.getDept().getCourseList().get(i).getSectionList().get(j).getDay().equals("Monday")) {
                            secDay = ", Wednesday";
                        } else if (AD.getDept().getCourseList().get(i).getSectionList().get(j).getDay().equals("Tuesday")) {
                            secDay = ", Thursday";
                        } else if (AD.getDept().getCourseList().get(i).getSectionList().get(j).getDay().equals("Wednesday")) {
                            secDay = ", Friday";
                        }
                    } else {
                        lt = lt.plusHours(3);
                    }

                    String timing = "";
                    String day = "";
                    timing = AD.getDept().getCourseList().get(i).getSectionList().get(j).getTime().toString() + " - " + lt.toString();
                    day = AD.getDept().getCourseList().get(i).getSectionList().get(j).getDay() + secDay;

                    tbModel.insertRow(tbModel.getRowCount(), new Object[]{AD.getDept().getCourseList().get(i).getSectionList().get(j).getName(),
                        day, timing,
                        AD.getDept().getCourseList().get(i).getSectionList().get(j).getRoom(),
                        AD.getDept().getCourseList().get(i).getSectionList().get(j).getRoomLimit(),
                        instrName});
                }
                break;
            }
        }
    }

    public ViewSectionsOfSelCourse(Admin ad, String c) {
        initComponents();
        AD = ad;
        course = c;
        cname.setText(c);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setText("View Sections");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Day", "Time", "Room", "Room Limit", "Instructor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Course name:");

        cname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], Admin ad, String c) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSectionsOfSelCourse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSectionsOfSelCourse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSectionsOfSelCourse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSectionsOfSelCourse.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSectionsOfSelCourse(ad, c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
